workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - sahklubkralj@gmail.com
        notify:
          success: true
          failure: false