name: sahovska_app
description: Oficijalna aplikacija šahovskog kluba za obaveštenja i komunikaciju
publish_to: 'none'
version: 1.0.0+1

# Production metadata
author: Šahovski Klub Team
homepage: https://shahovskiklub.com
repository: https://github.com/shahovskiklub/mobile-app
issue_tracker: https://github.com/shahovskiklub/mobile-app/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  
  # UI dependencies
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.3.0
  
  # State management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^15.1.2
  
  # Utility
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.6
  
  # File handling and storage
  image_picker: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Regular.ttf
    #     - asset: fonts/Roboto-Bold.ttf
    #       weight: 700